apiVersion: v1
data:
  prometheus.yml: |
    # filepath: /Users/venessa/Documents/Projects/DevOps/monitoring-app-v3/prometheus.yml
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]

      - job_name: "flask-backend"
        static_configs:
          - targets: ["server:5001"]
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: prometheus-config
